Issue1
1005hoon/app-review-crawler pull request #7
Opened 2023-04-23 14:16 UTC by Harrisommm

이게 머지 리퀘스트인가엽

2023-04-24 06:55 UTC, Harrisommm commented
@1005hoon 
Task
RSS 피드에서 리뷰 정보를 받아 리스트에 저장하였습니다
한글 리뷰가 깨지지 않게 utf8로 코딩하여 csv파일로 저장하였습니다


Issue
리뷰가 없는 경우, 리뷰 숫자가 적은 경우, 가끔 xml화 될때 깨지는 경우 코드가 crash 해서
 터지지 않게 exception handling 했습니다

2023-04-24 07:37 UTC, 1005hoon requested changes
위에 달아둔 커멘트 기반으로 수정작업 / 커밋 후 알려주세용! @Harrisommm

2023-04-25 06:38 UTC, Harrisommm commented on app.py
> +        url = "https://itunes.apple.com/kr/rss/customerreviews/page=%i/id=%i/sortby=mostrecent/xml?urlDesc=/customerreviews/id=%i/sortBy=mostRecent/xml" % (idx, appid, appid)
변경했습니당

2023-04-25 06:40 UTC, Harrisommm commented on app.py
> +def get_url_index(url):
변경해봤습니당

2023-04-25 06:48 UTC, Harrisommm commented on app.py
> +def get_url_index(url):
last_url = next(filter(lambda l: l['@rel'] == 'last', xml['feed']['link']))['@href']
    last_index = next(filter(lambda s: 'page=' in s, last_url.split('/'))).replace('page=', '')
    last_index = int(last_index)
    계속 에러가 나서... gpt의 힘을 빌려 처리해 보았습니다...

2023-04-25 06:58 UTC, Harrisommm commented on app.py
> +    appstore_crawler(app_id, outfile=outfile)
뒷부분 outfile은 csv 파일 이름 저장 포맷이고, 앞부분은 dataframe이어서요. 더 최적화 할수있는 방법이 있는지는 모르겠네요 ㅠㅠ

2023-04-25 06:59 UTC, Harrisommm commented on app.py
> +    last_index = [int(s.replace('page=', '')) for s in last_url.split('/') if ('page=' in s)][0]
last_url = next(filter(lambda l: l['@rel'] == 'last', xml['feed']['link']))['@href']
    last_index = next(filter(lambda s: 'page=' in s, last_url.split('/'))).replace('page=', '')
    last_index = int(last_index)
    계속 에러가 나서... gpt의 힘을 빌려 처리해 보았습니다...

2023-04-25 07:05 UTC, Harrisommm commented on app.py
> +        response = requests.get(url).content.decode('utf8')
1초 추가해보았습니다

2023-04-27 15:12 UTC, Harrisommm commented on README.md
> +
스위치로 한번 넣어봤습니다!

2023-04-28 02:01 UTC, 1005hoon approved these changes

2023-04-28 02:01 UTC, merged